kits: true
items:
  enableamountlimit: true
  silentamountlimit: true
  maxspawnamount: 20
tpa:
  expiration: 30
broadcasting:
  effectId: 42069
  # In Milliseconds (1000 for 1 second)
  defaultBroadcastDuration: 5000
  timeLimit: 25000
  repeatingInterval: 30000
  repeatingDuration: 6000
  repeatingMessages:
    - SupahBroadcasto
    - This is bla b
    - a a a 
afkchecker:
  timeout: 600