kits: true
items:
  enableamountlimit: true
  silentamountlimit: true
  maxspawnamount: 20
tpa:
  expiration: 30
broadcasting:
  effectId: 42069
  defaultBroadcastDuration: 5
  broadcastTimeLimit: 25
  repeatingBroadcastInterval: 300
  repeatingBroadcastStayTime: 6
  broadcastMessages:
    - SupahBroadcasto
    - This is bla b
    - a a a 
afkchecker:
  timeout: 600