kits: true
items:
  enableamountlimit: true
  silentamountlimit: true
  maxspawnamount: 20
tpa:
  expiration: 30
broadcasting:
  effectId: 42069
  defaultBroadcastDuration: 5
  broadcastTimeLimit: 25
  repeatingBroadcastInterval: 300
  repeatingBroadcastStayTime: 6
  broadcastMessages: {"SupahBroadcasto!!!!", "This is a SUPER broadcast!", "set repeatingBroadcastInterval to -1 to disable this!"}
  #Is this right ^^ I haven't used yaml since like 2015 lol
  
  